"use client";
import { useState, useEffect } from "react";
import { createClient } from "@/lib/supabase/client";
import { formatPrice } from "@/lib/utils";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Plus, Edit2, Trash2, Search } from "lucide-react";
import Image from "next/image";
import toast from "react-hot-toast";
export default function AdminProductsPage() {
  const [products, setProducts] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [showForm, setShowForm] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ name: "", slug: "", description: "", price: "", original_price: "", discount_percent: "", category: "", brand: "", images: "", stock: "", is_featured: false, is_deal: false });
  const load = async () => { try { const supabase = createClient(); const { data } = await supabase.from("products").select("*").order("created_at", { ascending: false }); setProducts(data || []); } catch {} finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const handleSave = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); try { const supabase = createClient(); const d = { name: form.name, slug: form.slug || form.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), description: form.description, price: Number(form.price), original_price: Number(form.original_price) || Number(form.price), discount_percent: Number(form.discount_percent) || 0, category: form.category, brand: form.brand, images: form.images.split(",").map(s => s.trim()).filter(Boolean), stock: Number(form.stock) || 0, is_featured: form.is_featured, is_deal: form.is_deal }; if (editingId) { await supabase.from("products").update(d).eq("id", editingId); toast.success("Updated!"); } else { await supabase.from("products").insert(d); toast.success("Added!"); } setShowForm(false); setEditingId(null); setForm({ name: "", slug: "", description: "", price: "", original_price: "", discount_percent: "", category: "", brand: "", images: "", stock: "", is_featured: false, is_deal: false }); load(); } catch(e: any) { toast.error(e?.message || "Failed"); } finally { setSaving(false); } };
  const handleDelete = async (id: string) => { if (!confirm("Delete?")) return; const supabase = createClient(); await supabase.from("products").delete().eq("id", id); toast.success("Deleted"); load(); };
  const filtered = products.filter(p => p.name.toLowerCase().includes(search.toLowerCase()) || p.category.includes(search.toLowerCase()));
  if (loading) return <div className="animate-pulse"><div className="h-64 bg-white rounded" /></div>;
  return (<div><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold">Products</h1><Button onClick={() => { setForm({ name: "", slug: "", description: "", price: "", original_price: "", discount_percent: "", category: "", brand: "", images: "", stock: "", is_featured: false, is_deal: false }); setEditingId(null); setShowForm(!showForm); }}><Plus size={16} /> Add</Button></div>
    {showForm && <div className="bg-white rounded-lg shadow-sm border p-6 mb-6"><form onSubmit={handleSave} className="grid grid-cols-1 md:grid-cols-2 gap-4"><Input label="Name" value={form.name} onChange={e => setForm({...form, name: e.target.value})} required /><Input label="Category" value={form.category} onChange={e => setForm({...form, category: e.target.value})} required /><Input label="Brand" value={form.brand} onChange={e => setForm({...form, brand: e.target.value})} /><Input label="Price" type="number" value={form.price} onChange={e => setForm({...form, price: e.target.value})} required /><Input label="Original Price" type="number" value={form.original_price} onChange={e => setForm({...form, original_price: e.target.value})} /><Input label="Stock" type="number" value={form.stock} onChange={e => setForm({...form, stock: e.target.value})} /><div className="md:col-span-2"><Input label="Images (comma separated URLs)" value={form.images} onChange={e => setForm({...form, images: e.target.value})} /></div><div className="flex gap-4"><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_featured} onChange={e => setForm({...form, is_featured: e.target.checked})} />Featured</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_deal} onChange={e => setForm({...form, is_deal: e.target.checked})} />Deal</label></div><div className="md:col-span-2 flex gap-3"><Button type="submit" loading={saving}>{editingId ? "UPDATE" : "ADD"}</Button><Button type="button" variant="ghost" onClick={() => setShowForm(false)}>Cancel</Button></div></form></div>}
    <div className="bg-white rounded-lg shadow-sm border p-4 mb-4"><div className="relative max-w-md"><input type="text" placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2 border rounded-sm text-sm focus:outline-none focus:ring-2 focus:ring-[#2874f0]" /><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /></div></div>
    <div className="bg-white rounded-lg shadow-sm border overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="text-left px-4 py-3">Product</th><th className="text-left px-4 py-3">Category</th><th className="text-left px-4 py-3">Price</th><th className="text-left px-4 py-3">Stock</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y">{filtered.map(p => <tr key={p.id} className="hover:bg-gray-50"><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="relative w-10 h-10 bg-gray-100 rounded"><Image src={p.images?.[0] || "/placeholder.png"} alt={p.name} fill className="object-contain p-1" sizes="40px" /></div><div><p className="font-medium line-clamp-1 max-w-[200px]">{p.name}</p><p className="text-xs text-gray-500">{p.brand}</p></div></div></td><td className="px-4 py-3 capitalize">{p.category}</td><td className="px-4 py-3 font-medium">{formatPrice(p.price)}</td><td className="px-4 py-3"><span className={p.stock === 0 ? "text-red-600" : "text-green-600"}>{p.stock}</span></td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => { setForm({ name: p.name, slug: p.slug, description: p.description || "", price: String(p.price), original_price: String(p.original_price), discount_percent: String(p.discount_percent), category: p.category, brand: p.brand || "", images: (p.images || []).join(", "), stock: String(p.stock), is_featured: p.is_featured, is_deal: p.is_deal }); setEditingId(p.id); setShowForm(true); }} className="text-blue-500"><Edit2 size={16} /></button><button onClick={() => handleDelete(p.id)} className="text-red-400"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>
  </div>);
}
