"use client";
import { useState, useEffect } from "react";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { EmptyState } from "@/components/ui/EmptyState";
import { MapPin, Plus, Trash2, Edit2 } from "lucide-react";
import toast from "react-hot-toast";
export default function AddressesPage() {
  const [addresses, setAddresses] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ full_name: "", phone: "", address_line1: "", address_line2: "", city: "", state: "", pincode: "" });
  const load = async () => { try { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (user) { const { data } = await supabase.from("addresses").select("*").eq("user_id", user.id).order("is_default", { ascending: false }); setAddresses(data || []); } } catch {} finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const handleSave = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); try { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; if (editingId) { await supabase.from("addresses").update(form).eq("id", editingId); toast.success("Updated!"); } else { await supabase.from("addresses").insert({ ...form, user_id: user.id, is_default: addresses.length === 0 }); toast.success("Added!"); } setShowForm(false); setEditingId(null); setForm({ full_name: "", phone: "", address_line1: "", address_line2: "", city: "", state: "", pincode: "" }); load(); } catch { toast.error("Failed"); } finally { setSaving(false); } };
  const handleDelete = async (id: string) => { if (!confirm("Delete?")) return; const supabase = createClient(); await supabase.from("addresses").delete().eq("id", id); toast.success("Deleted"); load(); };
  if (loading) return <div className="bg-white rounded-sm shadow-sm p-8 animate-pulse"><div className="h-6 w-40 bg-gray-200 rounded" /></div>;
  return (<div className="space-y-4">
    <div className="bg-white rounded-sm shadow-sm p-4 flex items-center justify-between"><h1 className="text-lg font-bold">My Addresses</h1><Button onClick={() => { setForm({ full_name: "", phone: "", address_line1: "", address_line2: "", city: "", state: "", pincode: "" }); setEditingId(null); setShowForm(!showForm); }} size="sm"><Plus size={16} /> Add</Button></div>
    {showForm && <div className="bg-white rounded-sm shadow-sm p-6"><form onSubmit={handleSave} className="grid grid-cols-1 md:grid-cols-2 gap-4"><Input label="Full Name" value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} required /><Input label="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} required /><div className="md:col-span-2"><Input label="Address Line 1" value={form.address_line1} onChange={(e) => setForm({ ...form, address_line1: e.target.value })} required /></div><Input label="City" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} required /><Input label="State" value={form.state} onChange={(e) => setForm({ ...form, state: e.target.value })} required /><Input label="Pincode" value={form.pincode} onChange={(e) => setForm({ ...form, pincode: e.target.value })} required /><div className="md:col-span-2 flex gap-3"><Button type="submit" loading={saving}>{editingId ? "UPDATE" : "SAVE"}</Button><Button type="button" variant="ghost" onClick={() => setShowForm(false)}>Cancel</Button></div></form></div>}
    {addresses.length === 0 && !showForm ? <EmptyState icon={<MapPin size={80} className="text-gray-300" />} title="No addresses" description="Add one for faster checkout." /> : addresses.map((a) => <div key={a.id} className="bg-white rounded-sm shadow-sm p-4"><p className="text-sm font-bold">{a.full_name} {a.is_default && <span className="text-xs bg-blue-50 text-[#2874f0] px-2 py-0.5 rounded ml-2">Default</span>}</p><p className="text-sm text-gray-600">{a.address_line1}, {a.city}, {a.state} - {a.pincode}</p><p className="text-xs text-gray-500 mt-1">Phone: {a.phone}</p><div className="flex gap-4 mt-3 pt-3 border-t"><button onClick={() => { setForm(a); setEditingId(a.id); setShowForm(true); }} className="text-xs text-[#2874f0] font-medium"><Edit2 size={12} className="inline mr-1" />Edit</button><button onClick={() => handleDelete(a.id)} className="text-xs text-red-500 font-medium"><Trash2 size={12} className="inline mr-1" />Delete</button></div></div>)}
  </div>);
}
